import fs from 'fs-extra';
import path from 'path';
import { validatePath } from './path-utils.js';

export function buildScssContent(fonts, urlAlias) {
	const families = new Map();
	for (const font of fonts) {
		if (!families.has(font.fontFamily)) families.set(font.fontFamily, []);
		families.get(font.fontFamily).push(font);
	}

	const orderedFonts = Array.from(families.entries())
		.sort(([a], [b]) => a.localeCompare(b))
		.flatMap(([family, familyFonts]) => {
			const ordered = [...familyFonts].sort((a, b) => {
				if (a.fontWeight !== b.fontWeight) return a.fontWeight - b.fontWeight;
				return a.fontStyle.localeCompare(b.fontStyle);
			});
			return ordered.map((font) => ({ family, font }));
		});

	let scss = '// Auto-generated by vite-plugin-fonts-converter\n';
	scss += '// Do not edit manually\n\n';

	for (const { family, font } of orderedFonts) {
		scss += '@font-face {\n';
		scss += `  font-family: '${family}';\n`;
		scss += `  src: url('${urlAlias}/${font.fileName}.woff2') format('woff2');\n`;
		scss += `  font-weight: ${font.fontWeight};\n`;
		scss += `  font-style: ${font.fontStyle};\n`;
		scss += '  font-display: swap;\n';
		scss += '}\n\n';
	}

	const familyNames = Array.from(families.keys()).sort((a, b) => a.localeCompare(b));
	if (familyNames.length > 0) {
		scss += '// SCSS variables\n';
		for (const family of familyNames) {
			const varName = family.toLowerCase().replace(/\s+/g, '-');
			scss += `$font-${varName}: '${family}', sans-serif;\n`;
		}
	}

	return scss;
}

export async function writeScss(scssOutput, fonts, urlAlias) {
	validatePath(scssOutput);

	const content = buildScssContent(fonts, urlAlias);
	await fs.ensureDir(path.dirname(scssOutput));

	try {
		const existing = await fs.readFile(scssOutput, 'utf8');
		if (existing === content) return false;
	} catch {
		// file doesn't exist
	}

	await fs.writeFile(scssOutput, content);
	return true;
}
